### ISSUE TITLE
semantic release

### ISSUE THREAD

**Issue by UziTech** [atom-ide-community/atom-languageclient#90]
v1.0.0 is published :tada:

We should setup semantic release.

@aminya do you want to take care of that? I allowed [atom-ide-community](https://www.npmjs.com/~atom-ide-community) to publish [atom-languageclient](https://www.npmjs.com/package/atom-languageclient) so we can use an organization token on NPM.

You should also set up the deps update github action so we don't get so many update commits. Just make sure to create the PR with a GitHub PAT so tests run.

**Comment by aminya** [comment]
Yes. We should set the semantic release job. I can help with that.

Regarding the dependencies, I will add the proper job for bumping the deps. I can set up two separate jobs, one for devDeps and one for deps. This allows us to not merge the devDeps updates until it is a considerable change.

**Comment by aminya** [comment]
We should create a semantic release config for npm packages, so we can use it for all the npm packages.

Some examples: 
https://github.com/hexonet/semantic-release-github-npm-config/blob/master/.releaserc.json
https://github.com/traverson/semantic-release-config/blob/master/shareable-config.json
https://github.com/artemv/simple-semantic-config/blob/master/index.js

**Comment by UziTech** [comment]
Sounds good to me. Can you take care of that?

**Comment by aminya** [comment]
I am afraid I am busy these days.

**Comment by UziTech** [comment]
ok I'll make a minimal config template.

**Comment by aminya** [comment]
The config package is registered. Just use our previous template and change its config:

```yaml
       - name: Release 🎉
         uses: cycjimmy/semantic-release-action@v2
         with:
           extends: |
             @atom-ide-community/semantic-release-npm-config
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           NPM_TOKEN: ${{ secrets.NPM_TOKEN  }}
```
